site_name: Handbook
site_url: https://www.cartman.fi/handbook/

# Make documentation artifact easier to browse locally
use_directory_urls: false

nav:
  - Handbook:
    - index.md
    - Mission & Vision: index/mission-vision.md
    - Core Values: index/core-values.md
    - Code of Conduct: index/code-of-conduct.md
  - Working at Cartman:
    - working-at-cartman/index.md
    - Time logging: working-at-cartman/time-logging.md
    - Oulu office: working-at-cartman/oulu-office.md
    - Health care: working-at-cartman/health-care.md
  - Technical Excellence:
    - tech/index.md
    - tech/tech-radar.md
  - Security: security-policy.md

theme:
  name: material
  language: en
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Cartman-Digital
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cartmandigital/


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.blocks.html

copyright: Copyright &copy; 2024 <a href="https://www.cartman.fi/">Cartman Digital</a>.

repo_name: Cartman-Digital/handbook
repo_url: https://github.com/Cartman-Digital/handbook
edit_uri: edit/main/docs/

plugins:
  - git-authors:
      show_email_address: false
      authorship_threshold_percent: 5
  - git-revision-date-localized:
      type: timeago
  - search