version: '3'

tasks:
  run:
    desc: Serve documentation locally via http://127.0.0.1:8000/
    cmds:
      - mkdocs serve
    interactive: true

  build:
    desc: Generate HTML
    sources:
      - ./**/*
      - exclude: ./target/**/*
    generates:
      - ./target/**/*
    cmds:
      - task: clean
      - mkdocs build -d target

  clean:
    desc: Clean target directory
    cmds:
      - rm -rf target/