name: Nix Flake actions

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix run . --build
